name: Run SQLGo Python Script

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11,3.10,3.9,3.8,3.7,3.6'          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any requirements

      - name: Run Python script
        run: python sqlgo.py -u http://testasp.vulnweb.com/showthread.asp?id=3 --port=80 --level=5 --delay-time=1 --tamper=space2randomblank  --dump --batch --beep --verbose=5
